/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.minimarketgg.igu.pedidos;

import com.mycompany.minimarketgg.logica.Pedido;
import com.mycompany.minimarketgg.logica.PedidoDao;
import com.mycompany.minimarketgg.logica.Proveedor;
import com.mycompany.minimarketgg.logica.ProveedorDao;
import com.mycompany.minimarketgg.util.IconoUtil;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AgregarPedidos extends javax.swing.JFrame {

    private PedidoDao pdd = new PedidoDao();
    private ProveedorDao pvd = new ProveedorDao();
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    public AgregarPedidos() {
        this.setTitle("AgregarPedidos");
        setResizable(false);
        IconoUtil.establecerIcono(this);
        initComponents();
        llenarComboBoxProveedor();
    }

    private void llenarComboBoxProveedor() {
        // Llenar el JComboBox con los nombres de los proveedores
        ArrayList<String> nombresProveedores = pvd.obtenerNombresProveedores();
        for (String nombre : nombresProveedores) {
            comboBoxProveedorPedido.addItem(nombre);
        }
    }

    private boolean camposCompletos() {
        return MiDate.getDate() != null &&
               comboBoxProveedorPedido.getSelectedIndex() != -1;
    }

    private void limpiarCampos() {
        MiDate.setDate(null);
        comboBoxProveedorPedido.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBoxProveedorPedido = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        MiDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Pedidos");

        jLabel2.setText("Fecha");

        jLabel3.setText("Proveedores");

        comboBoxProveedorPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un proveedor" }));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        MiDate.setDateFormatString("yyyy-MM-dd");
        MiDate.setMinSelectableDate(new java.util.Date(-62135747934000L));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxProveedorPedido, 0, 153, Short.MAX_VALUE)
                            .addComponent(MiDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnCancelar)
                        .addGap(54, 54, 54)
                        .addComponent(btnGuardar)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(MiDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxProveedorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      if (!camposCompletos()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos");
            return;
        }

        String nombreProveedor = comboBoxProveedorPedido.getSelectedItem().toString();
        Proveedor proveedor = pvd.obtenerProveedorPorNombre(nombreProveedor);

        if (proveedor == null) {
            JOptionPane.showMessageDialog(this, "Proveedor no encontrado.");
            return;
        }

        // Obtener la fecha del JDateChooser y convertirla a String
        String fechaPedido = sdf.format(MiDate.getDate());

        // Crear un nuevo objeto Pedido
        Pedido nuevoPedido = new Pedido(0, fechaPedido, proveedor.getId(), 0.0); // Ajustar el constructor según la clase Pedido

        // Intentar agregar el pedido
        if (pdd.agregarPedido(nuevoPedido)) {
            JOptionPane.showMessageDialog(this, "Pedido guardado correctamente.");
            limpiarCampos();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el pedido.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser MiDate;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboBoxProveedorPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
