/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.minimarketgg.igu.pedidos;

import com.mycompany.minimarketgg.logica.Pedido;
import com.mycompany.minimarketgg.logica.PedidoDao;
import com.mycompany.minimarketgg.util.IconoUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class EliminarPedidos extends javax.swing.JFrame {

    /**
     * Creates new form EliminarPedidos
     */
    public EliminarPedidos() {
        this.setTitle("Eliminar Pedido");
        setResizable(false);
        IconoUtil.establecerIcono(this);
        initComponents();
        
        actualizarComboBoxPedido();
    }
    
    private void actualizarComboBoxPedido() {
        PedidoDao pedidoDao = new PedidoDao();
    comboBoxPedido.removeAllItems();
    comboBoxPedido.addItem("Elige un ID");
    pedidoDao.obtenerPedidos().forEach((pedido) -> {
        comboBoxPedido.addItem(String.valueOf(pedido.getId()));
    });
}
    
    private void limpiarFormulario() {
        comboBoxPedido.setSelectedIndex(0);
        chkConfirmaciónPedido.setSelected(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxPedido = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        chkConfirmaciónPedido = new javax.swing.JCheckBox();
        btnCancelarEliminarPedido = new javax.swing.JButton();
        btnGuardarEliminarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Eliminar Pedido");

        jLabel2.setText("Elige un ID");

        comboBoxPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un ID para eliminar" }));
        comboBoxPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPedidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Marca para eliminar");

        chkConfirmaciónPedido.setText("¿Estás seguro de eliminar este pedido?");
        chkConfirmaciónPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkConfirmaciónPedidoActionPerformed(evt);
            }
        });

        btnCancelarEliminarPedido.setText("Cancelar");
        btnCancelarEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEliminarPedidoActionPerformed(evt);
            }
        });

        btnGuardarEliminarPedido.setText("Eliminar");
        btnGuardarEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEliminarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkConfirmaciónPedido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(comboBoxPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnCancelarEliminarPedido)
                        .addGap(53, 53, 53)
                        .addComponent(btnGuardarEliminarPedido)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chkConfirmaciónPedido))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEliminarPedido)
                    .addComponent(btnGuardarEliminarPedido))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPedidoActionPerformed

    private void btnCancelarEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEliminarPedidoActionPerformed
         this.dispose();
    }//GEN-LAST:event_btnCancelarEliminarPedidoActionPerformed

    private void btnGuardarEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEliminarPedidoActionPerformed
           Object selectedItem = comboBoxPedido.getSelectedItem();
        if (selectedItem != null) {
            int id = Integer.parseInt((String) selectedItem);
            if (chkConfirmaciónPedido.isSelected()) {
                // La casilla de verificación está marcada, procede con la eliminación de la categoría
                PedidoDao pedidoDao = new PedidoDao();
                Pedido pedido = pedidoDao.obtenerPedidoPorId(id);
                if (pedido != null) {
                    // Categoría encontrada, proceder con la eliminación
                    if (pedidoDao.eliminarPedido(pedido.getId())) {
                        JOptionPane.showMessageDialog(null, "Pedido eliminado correctamente.");
                        limpiarFormulario();
                        this.dispose();
                        limpiarFormulario();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al eliminar el pedido.");
                        limpiarFormulario();
                    }
                } else {
                    // Categoría no encontrada
                    JOptionPane.showMessageDialog(null, "El pedido no existe en la base de datos.");
                }
            } else {
                // La casilla de verificación no está marcada, informar al usuario que debe confirmar la eliminación
                JOptionPane.showMessageDialog(null, "Por favor, marque la casilla de confirmación para eliminar el pedido.");
            }
        }
    }//GEN-LAST:event_btnGuardarEliminarPedidoActionPerformed

    private void chkConfirmaciónPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkConfirmaciónPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkConfirmaciónPedidoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEliminarPedido;
    private javax.swing.JButton btnGuardarEliminarPedido;
    private javax.swing.JCheckBox chkConfirmaciónPedido;
    private javax.swing.JComboBox<String> comboBoxPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
