package com.mycompany.minimarketgg.igu;

import com.mycompany.minimarketgg.igu.productos.Inventario;
import com.mycompany.minimarketgg.logica.Usuario;
import com.mycompany.minimarketgg.usuarios.Usuarios;
import com.mycompany.minimarketgg.util.IconoUtil;
import com.mycompany.minimarketgg.util.PantallaUtil;
import com.mycompany.minimarketgg.ventas.Ventas;
import javax.swing.JFrame;

public class Menu extends javax.swing.JFrame {
    /**
     * Creates new form Menu
     * @param anchoPantalla
     * @param altoPantalla
     */
    
       private Usuario usuario;

    public Menu(Usuario usuario) {
        initComponents();
        this.usuario = usuario;  // Asigna el usuario autenticado
        actualizarLabelUsuario();
        configurarPermisos();  // Configura los permisos basados en el rol del usuario
        this.setTitle("MiniMarket GG");
        IconoUtil.establecerIcono(this);
    }

    public Menu(int anchoPantalla, int altoPantalla) {
        initComponents();
        this.setSize(anchoPantalla, altoPantalla);
        this.setTitle("MiniMarket GG");
        IconoUtil.establecerIcono(this);
    }
     
   
    
    private void configurarPermisos() {
        switch (usuario.getRol().getTipoRol()) {
            case "Administrador":
                // El administrador tiene acceso a todo
                break;
            case "Asistente Ventas":
                btnInventario.setEnabled(false);
                usuarioBtn.setEnabled(false);
                break;
            case "Asistente Inventario":
                btnVentas.setEnabled(false);
                usuarioBtn.setEnabled(false);
                break;
            default:
                // Deshabilitar todos los botones si el rol no es reconocido
                btnInventario.setEnabled(false);
                btnVentas.setEnabled(false);
                usuarioBtn.setEnabled(false);
                break;
            }
    }
    
    private void actualizarLabelUsuario() {
        if (this.usuario != null) {
            jLabelUsuarioRegistrado.setText("Hola!, " + this.usuario.getNombre());
        } else {
            jLabelUsuarioRegistrado.setText("User not identified");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVentas = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();
        btnInventario = new javax.swing.JButton();
        usuarioBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabelUsuarioRegistrado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVentas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/minimarketgg/imagenes/Alegre2.png"))); // NOI18N

        btnInventario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        usuarioBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        usuarioBtn.setText("Usuarios");
        usuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioBtnActionPerformed(evt);
            }
        });

        btnLogout.setText("Cerrar Sesión");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("MinimarketGG Menú:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnLogout)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelUsuarioRegistrado.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelUsuarioRegistrado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUsuarioRegistrado.setText("Hola! , ");
        jLabelUsuarioRegistrado.setForeground(new java.awt.Color(25, 25, 112));
        actualizarLabelUsuario();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(lblIcon))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabelUsuarioRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(usuarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelUsuarioRegistrado))
                .addGap(32, 32, 32)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
                                                    
    Inventario ventana = new Inventario(usuario);
    ventana.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximizar la ventana a pantalla completa
    ventana.setVisible(true);
    ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    
    // Cerrar la ventana actual
    this.dispose();

    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        JFrame ventanaVentas = new JFrame();
    Ventas ventasPanel = new Ventas(usuario); // Pasar el objeto usuario al constructor de Ventas
    ventanaVentas.setContentPane(ventasPanel);
    ventanaVentas.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximizar la ventana a pantalla completa
    ventanaVentas.setVisible(true);
    ventanaVentas.setLocationRelativeTo(null);
    IconoUtil.establecerIcono(ventanaVentas);
    ventanaVentas.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    // Cerrar la ventana actual
    this.dispose();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void usuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioBtnActionPerformed
    Usuarios ventanaUsuarios = new Usuarios(usuario);
    ventanaUsuarios.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximizar la ventana a pantalla completa
    ventanaUsuarios.setVisible(true);
    ventanaUsuarios.setLocationRelativeTo(null);
    ventanaUsuarios.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    // Cerrar la ventana actual
    this.dispose();
    }//GEN-LAST:event_usuarioBtnActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // Cerrar la ventana actual
        this.dispose();

        // Mostrar la ventana de inicio de sesión
        Login loginPanel = new Login(PantallaUtil.obtenerAnchoPantalla(), PantallaUtil.obtenerAltoPantalla()); // Pasar el tamaño de la pantalla
        loginPanel.setResizable(false);
        loginPanel.setVisible(true);
        loginPanel.setSize((int) (PantallaUtil.obtenerAnchoPantalla() * 0.62), (int) (PantallaUtil.obtenerAltoPantalla() * 0.67));
        loginPanel.setLocationRelativeTo(null);
        loginPanel.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabelUsuarioRegistrado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JButton usuarioBtn;
    // End of variables declaration//GEN-END:variables
}
